Repository lion-packages/spreadsheet, pull requests merged in 2025-03, with the labels that each got.

#15 Added Github Actions configuration
  .github/workflows/php.yml
  composer.json
  phpunit.xml
Labels: continuous integration, dependencies

#16 Added dependabot
  .github/dependabot.yml
Labels: continuous integration

#18 PHPLint is integrated
  .github/workflows/php.yml
  .gitignore
  composer.json
Labels: continuous integration, dependencies

#19 Update README.md
  .github/README.md
Labels: documentation

#21 Infection is integrated
  .github/workflows/php.yml
  Dockerfile
Labels: continuous integration
